12 paginate results of findblocksbyproposer 68
NightfallRollup/nightfall_3.5 pull request #17
Opened 2023-03-13 15:12 UTC by pawelgrzybek

fix #12

2023-03-14 07:32 UTC, druiz0992 requested changes
Can you provide a test for these changes? Current tests do not check what happens if pagination is required

Also, is it possible to pass an additional optional argument which is the first item to return?

2023-03-14 09:43 UTC, pawelgrzybek commented
Hi @druiz0992 

1. Sure i will add tests for this one.
2. This is not something that we need to use at this point. Why does it need to be implemented now?

2023-03-14 10:00 UTC, druiz0992 commented
> 



> Hi @druiz0992
> 

> 2. This is not something that we need to use at this point. Why does it need to be implemented now?

ok, we may not need to, but for example, in the case you are implementing, retrieving the whole list of blocks submitted by a single proposer over an over seems unnecessary. It would be more efficient to just provide the starting point.

2023-03-14 17:47 UTC, druiz0992 approved these changes

2023-03-21 17:16 UTC, daveroga approved these changes

2023-03-21 17:59 UTC, merged