Worker with rapidsnark server prover
NightfallRollup/nightfall_3.5 pull request #19
Opened 2023-03-14 06:56 UTC by daveroga

## What does this implement/fix? Explain your changes.
Update worker and move from snarkjs to rapidsnark for faster proof generartion.
Instead of using a prover executable for the proof generation we'll use a server with an endpoint that will generate the witness and the proof from the inputs.

## Does this close any currently open issues?
https://github.com/NightfallRollup/nightfall-config/issues/38

## What commands can I run to test the change? 
Run `setup-nightfall` for the generation of the `local-rapidsnark` container and then `start-nightfall` with `ALWAYS_DO_TRUSTED_SETUP=true` after pruning docker images first for the `worker`.
Then you can run any ERC test.

## Any other comments?
No

2023-03-16 21:44 UTC, druiz0992 submitted a review, later dismissed

2023-03-17 08:50 UTC, druiz0992 reviewed
how do you select which prover you want to use?

2023-03-17 12:11 UTC, daveroga commented
> how do you select which prover you want to use?

Yes, I'm missing this...
I'll add the option to be able to select SNARKJS / RAPIDSNARK in the worker container.

2023-03-19 09:21 UTC, druiz0992 approved these changes

2023-03-21 17:58 UTC, druiz0992 requested changes
how do you select which prover you want to use?

2023-03-21 17:58 UTC, druiz0992 commented on bin/setup-nightfall
> +if [ "$SKIP_RAPIDSNARK_BUILD" == "" ]; then
Whats the relationship between `SKIP_RAPIDSNARK_BUILD` and `PROVER_TYPE`? Why do we have two different variables? I would assume that if we skip build of rapidsnarks its because prover type is not rapidsnark? If this is the case, can we make it a single env variable?

2023-03-22 08:43 UTC, druiz0992 approved these changes

2023-03-22 22:02 UTC, israelboudoux commented on worker/src/utils/rapidsnarkProver.mjs
> +  await callInput(input, circuit);
Hey @daveroga, I remember you mentioned that the rapisnark server doesn't support concurrent calls. I didn't see any sort of call serialization in this PR. Where is it?

2023-03-24 13:24 UTC, daveroga commented on worker/src/utils/rapidsnarkProver.mjs
> +  await callInput(input, circuit);
The concurrency is managed at the server side (C++ code) and there there is a mutex. So in the case the server is doing a computation of the proof and you call a new generation of a proof you wait in the mutex until the last proof is finished.
No need to manage this in our NodeJs code.

2023-03-28 07:47 UTC, israelboudoux approved these changes

2023-04-03 09:12 UTC, merged