optimized verifier
NightfallRollup/nightfall_3.5 pull request #23
Opened 2023-03-18 16:34 UTC by druiz0992

## What does this implement/fix? Explain your changes.
Removed dependency on snarkjs verifier and included new version that performs circuit caching for faster results

## Does this close any currently open issues?
No

## What commands can I run to test the change? 
Any existing test uses this new verifier

## Any other comments?
No

2023-03-19 17:31 UTC, pawelgrzybek requested changes

2023-03-19 17:31 UTC, pawelgrzybek commented on nightfall-optimist/package.json
> +    "ffjavascript": "^0.2.57",
based on what we discussed before about licensing, keep in mind this is released under GPL type of license.

```json
{
  "license": "GPL-3.0"
}

```

https://github.com/iden3/ffjavascript#license

2023-03-19 18:27 UTC, druiz0992 commented on nightfall-optimist/package.json
> +    "ffjavascript": "^0.2.57",
Ok. We were using snarkjs before with the same license, so no problem for me

2023-03-19 18:53 UTC, pawelgrzybek commented on nightfall-optimist/package.json
> +    "ffjavascript": "^0.2.57",
Let's discuss this tomorrow please. I think I have some more insights about the licensing, but I would prefer to keep it offline.

2023-03-20 14:25 UTC, daveroga commented on nightfall-optimist/src/services/utils/groth16_verify.mjs
> +  logger,
And what about `circuitHash` parameter?
I think it could be removed and doing something like 
```
const circuitHash =  H(vk_verifier.vk_gamma_2, vk_verifier.vk_delta_2, vk_verifier.vk_alpha_1, vk_verifier.vk_beta_2)
```
inside the `groth16Verify` function where `H` could be any hash function like `sha256` will avoid passing another parameter and will verify that you are not doing wrong things like passing a `vk` that does not match with the `circuitHash` of the called function and I think it's more general.

2023-03-20 15:14 UTC, imagobea commented
Hello @druiz0992 

The PR description implies that these changes improve `verifyProof` function (called by `checkTransaction`).

I understand that caching can speed things up, but it would be good to document the improvement. What were the figures before/after? Did you measure `verifyProof`, `checkTransaction` or the "parent" process, eg `checkBlock`?

Would be interesting to know how much time the "inner processes" take over the main calls, for example `verifyProof` over `checkTransaction`, `checkTransaction` over `checkBlock`... 

Feels like you did some preliminary assessment which would be good to have on the PR.
Cheers!

2023-03-20 17:33 UTC, druiz0992 commented on nightfall-optimist/src/services/utils/groth16_verify.mjs
> +  logger,
i understand what @daveroga suggests, and why it can make sense. My problem with this approach is that i have to compute a hash everytime i call verify function, which will make it slower. So, we are trying to make something faster, but we are artificially slowing it down. So, that's what i don't like. What about if we pass the ´circuitHash` as an optional parameter? if its passed, then we can have the optimization. If not, verification function works as it did before?

2023-03-21 07:01 UTC, daveroga commented on nightfall-optimist/src/services/utils/groth16_verify.mjs
> +  logger,
Ok, I see your point for the case of Nightfall using it like this. `circuitHash`will be something like `cacheId` because as I said it's not enforced to be related with `vk` if calculated outside the function. But with the optional parameter could work.

2023-03-21 19:57 UTC, druiz0992 commented on nightfall-optimist/src/services/utils/groth16_verify.mjs
> +  logger,
It’s done

2023-03-21 20:10 UTC, pawelgrzybek commented
I am very sorry, I would love to help with the review of this one, but this is way outside of my understanding of whats going on here. I would rely more one more experienced reviews by @imagobea @eugypalu @daveroga @israelboudoux on this one.

2023-03-22 10:09 UTC, daveroga approved these changes

2023-03-22 21:44 UTC, israelboudoux commented on nightfall-optimist/src/services/utils/curves.mjs
> +      .match(/[A-Za-z0-9]+/g)
Just a little thing, since the name is already uppercased, you don't need the lower case chars in the regex.

2023-03-22 21:51 UTC, israelboudoux approved these changes

2023-03-23 00:24 UTC, druiz0992 commented on nightfall-optimist/src/services/utils/curves.mjs
> +      .match(/[A-Za-z0-9]+/g)
sorry, but im not touching this function. ITs part of snarkjs library and i will not modify it.

2023-03-23 00:25 UTC, merged