check last timber is saved
NightfallRollup/nightfall_3.5 pull request #26
Opened 2023-03-18 17:29 UTC by druiz0992

## What does this implement/fix? Explain your changes.
This PR fixes a bug during block generation. It is possible that if there are many transactions in the previous block, the timber is not saved by the time a new block is being built. This PR detects this case and builds a new block based on expected timber rather than on actual timber.

## Does this close any currently open issues?
No

## What commands can I run to test the change? 

## Any other comments?

2023-03-19 17:18 UTC, pawelgrzybek requested changes

2023-03-19 17:18 UTC, pawelgrzybek commented on nightfall-optimist/src/classes/block.mjs
> +    const timberBlockNumberL2 = await getNumberOfL2Blocks();
This should be fetched simultaneously with `getLatestBlockInfo` a few lines above. Like so:

```js
const [{ blockNumberL2: dbPrevBlockNumberL2, blockHash: dbBlockHash }, timberBlockNumberL2] =
      await Promise.all([getLatestBlockInfo(), getNumberOfL2Blocks()]);
```

2023-03-19 18:31 UTC, druiz0992 commented on nightfall-optimist/src/classes/block.mjs
> +    const timberBlockNumberL2 = await getNumberOfL2Blocks();
It’s not needed. There are read from different collections, updated at different times. So, there is no guarantee that data is more in sync. But I can do the change if you insist

2023-03-19 18:56 UTC, pawelgrzybek commented on nightfall-optimist/src/classes/block.mjs
> +    const timberBlockNumberL2 = await getNumberOfL2Blocks();
I dont insist. I assume there are two individual calls and the second one is not dependant one the 1st one. Keep it as it is then.

2023-03-20 08:03 UTC, druiz0992 commented on nightfall-optimist/src/classes/block.mjs
> +    const timberBlockNumberL2 = await getNumberOfL2Blocks();
looks better your way so i made the change

2023-03-20 09:51 UTC, pawelgrzybek approved these changes

2023-03-20 09:55 UTC, israelboudoux approved these changes

2023-03-20 09:56 UTC, merged