refactor optimist
NightfallRollup/nightfall_3.5 pull request #30
Opened 2023-03-18 22:27 UTC by druiz0992

## What does this implement/fix? Explain your changes.
Refactor optimisit

## Does this close any currently open issues?
No

## What commands can I run to test the change? 

## Any other comments?

2023-03-22 11:54 UTC, daveroga approved these changes

2023-03-31 05:55 UTC, imagobea requested changes
Hello @druiz0992 

Sorry to be a pain. I'm requesting changes but only because I'd like to understand better what you did.

I have left a few comments where I'm asking for a bit of detail - what you did, or why you think the change is needed.

It's good to document decisions. You may want to do the same on the client PR (?).

Much appreciated!! :pray: :pray: :pray:

2023-03-31 05:55 UTC, imagobea commented on nightfall-optimist/src/services/transaction-checker.mjs
Please explain refactor in this file

2023-03-31 05:55 UTC, imagobea commented on nightfall-optimist/src/services/check-block.mjs
Please explain refactor in this file

2023-03-31 05:55 UTC, imagobea commented on nightfall-optimist/src/services/block-assembler.mjs
Please explain refactor in this file. Do you think we need this if "nightfall-node" includes removing this websockets layer?

2023-03-31 05:55 UTC, imagobea commented on nightfall-optimist/src/event-handlers/block-proposed.mjs
Please explain refactor in this file. I can see that you remove the logic for challenging blocks in case of error, but I'm failing to see where this is now, sorry!!

2023-03-31 11:40 UTC, druiz0992 commented on nightfall-optimist/src/services/transaction-checker.mjs
This code is terrible and i got rid of it
```
  for (const [index, commitment] of transaction.commitments.entries()) {
    if (commitment !== ZERO) {
      if (checkDuplicatesInMempool) {
        const transactionMempoolHigherFee = await getMempoolTransactionByCommitment(
          commitment,
          transaction.fee,
        );
...
```
Basically, its reading dB for every single commitment included in a transaction

A few lanes later, this code is again retrieving transaction info from a commitment. 
```
      if (checkDuplicatesInL2) {
        // Search if there is any transaction in L2 that already contains the commitment
        const transactionL2 = await getTransactionL2ByCommitment(
          commitment,
          transactionBlockNumberL2,
```

This code can be done reading dB just once per transaction. Same with the `checkDuplicateNullifer()` function

2023-03-31 11:42 UTC, druiz0992 commented on nightfall-optimist/src/services/check-block.mjs
Just encapsulated code in functions for better clarity. No changes in functionality done here

2023-03-31 11:44 UTC, druiz0992 commented on nightfall-optimist/src/event-handlers/block-proposed.mjs
Removed code bits should be part of `check-block` now.  This file just encapsulates code in functions for better clarity.

2023-03-31 15:55 UTC, imagobea approved these changes
Many thanks @druiz0992 , you're good to go!! :rocket: Cheers

2023-04-03 09:13 UTC, merged