Optimist state sync pagination
NightfallRollup/nightfall_3.5 pull request #31
Opened 2023-03-20 14:36 UTC by pawelgrzybek

## What does this implement/fix? Explain your changes.

When optimist sync is triggered, it is going to chunk blocks to avoid replaying all events at once.

## Does this close any currently open issues?

#9 

## What commands can I run to test the change?

```
cd common-files && NODE_CONFIG_DIR=../config mocha --timeout 0 --bail --exit test/calculate-block-chunks.test.mjs
```

## Any other comments?

If you prefer to use an other value than 1000 as a default block chunk, I am happy to change it. For now it shouldn't make any difference until it is not prod deploy.

2023-03-20 16:53 UTC, druiz0992 requested changes
`CONFIRMATIONS` env variable should not be mixed with `STATE_SYNC_BLOCKS_CHUNK`

2023-03-20 17:43 UTC, druiz0992 commented
Sync test is failing. This is the error reported:
```optimist_1                 | [2023-03-20 15:47:56.096] ERROR: pastShieldEvents is not iterable
optimist_1                 |     err: {
optimist_1                 |       "type": "TypeError",
optimist_1                 |       "message": "pastShieldEvents is not iterable",
optimist_1                 |       "stack":
optimist_1                 |           TypeError: pastShieldEvents is not iterable
optimist_1                 |               at syncState (file:///app/src/services/state-sync.mjs:87:10)
optimist_1                 |               at processTicksAndRejections (node:internal/process/task_queues:96:5)
optimist_1                 |               at async initialBlockSync (file:///app/src/services/state-sync.mjs:176:7)
optimist_1                 |               at async main (file:///app/src/index.mjs:60:5)
optimist_1                 |     }
```

2023-03-21 14:45 UTC, daveroga approved these changes

2023-03-21 15:01 UTC, imagobea commented on nightfall-optimist/src/routes/block.mjs
> +    logger.debug(`block make-now endpoint received POST`);
The log shouldn't be needed at all since `httpUtils` logs some info for all requests/responses

2023-03-21 16:15 UTC, pawelgrzybek commented on nightfall-optimist/src/routes/block.mjs
> +    logger.debug(`block make-now endpoint received POST`);
For the sake of correctness. We can open a task and remove individual logs like that in one go, but that would be out of scope of this issue.

2023-03-21 16:39 UTC, druiz0992 approved these changes

2023-03-21 16:39 UTC, merged